version: "2.3"
services:
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: worker
    env_file: .env

networks:
  default:
    external: true
    name: gateway