name: Release

on:
  release:
    types: [created]
    paths:
      - service-worker/**

defaults:
  run:
    working-directory: service-worker

jobs:
  deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p "${{ secrets.REGISTRY_PASSWORD }}"
     # Build the Docker image
    - name: Get release tag
      id: vars
      run: echo ::set-output name=RELEASE_TAG::${GITHUB_REF/refs\/tags\//}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: service-worker/docker/Dockerfile
        context: ./service-worker
        push: true
        tags: ${{ secrets.SERVICE_WORKER_IMAGENAME }}:${{ steps.vars.outputs.RELEASE_TAG }}
