name: Release

on:
  release:
    types: [created]
    paths:
      - core-service/**

defaults:
  run:
    working-directory: core-service

jobs:
  deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p "${{ secrets.REGISTRY_PASSWORD }}"
     # Build the Docker image
    - name: Get release tag
      id: vars
      run: echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        file: core-service/docker/Dockerfile
        context: ./core-service
        push: true
        tags: ${{ secrets.CORE_SERVICE_IMAGENAME_PROD }}:${{ env.RELEASE_TAG }}
    
    # GitOps
    - name: GitOps ArgoCD Setup
      run: |
        echo "${{ secrets.GITLAB_ARGOCD_KEY }}" > /tmp/gitlab-deploy-ssh-key
        chmod 600 /tmp/gitlab-deploy-ssh-key
        export GIT_SSH_COMMAND="ssh -i /tmp/gitlab-deploy-ssh-key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone ${{ secrets.GITLAB_ARGOCD_REPOSITORY }}
    - name: GitOps ArgoCD Update Image Tag
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.spec.template.spec.containers[0].image = "${{ secrets.CORE_SERVICE_IMAGENAME_PROD }}:${{ env.RELEASE_TAG }}"' 'core-service/jds-terraform-gke/k8s/portal-jabar-app/production-jcloud/deployment.yaml'

    - name: GitOps ArgoCD Create Branch, Commit, Push
      run: |
        export GIT_SSH_COMMAND="ssh -i /tmp/gitlab-deploy-ssh-key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        cd jds-terraform-gke/k8s/portal-jabar-app/production-jcloud
        git config user.email "github-action@github.com"
        git config user.name "Github Action"
        git checkout -b portal-jabar-api-release-production
        git add deployment.yaml
        git commit -m "Portal Jabar API Release to Production"
        git push origin portal-jabar-api-release-production -o merge_request.description="# Overview \n\n - Portal Jabar API release to production \n\n ## Evidence \n\n - title: Portal Jabar API release to production \n - project: Portal Jabar \n - participants:  " -o merge_request.create
