name: CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      working-directory: ./core-service/src
      run: go build -v ./...

    - name: Test
      working-directory: ./core-service/src
      run: go test -v ./... -coverprofile coverage.out

    - name: Set Up Codeclimate and Send Report Codeclimate
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORT_ID }}
      with:
        coverageLocations: ./core-service/src/coverage.out
