name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      working-directory: ./core-service/src
      run: go build -v ./...

    - name: Installing codeclimate
      working-directory: ./core-service/src
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build  

    - name: Test
      working-directory: ./core-service/src
      run: go test -v ./... -coverprofile=./c.out && go tool cover -html=./c.out -o ./coverage.html

    - name: Send codeclimate
      working-directory: ./core-service/src
      env: 
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORT_ID }}
      run: |
        ./cc-test-reporter after-build --prefix "github.com/jabardigitalservice/portal-jabar-services/core-service/src"
